### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [13IEZ/slider_repair-design#1]
1. Слайдер должен быть зацикленным
2. Картинки не подгружаются, потому что вы меняете стили динамически в `index.html` и поиск картинки идет относительно этого файла
3. А что, если я попрошу добавить еще три слайда? Насколько увеличится ваш код? Вы используете неправильный поход. Посмотрите [пример](https://jsfiddle.net/pnkbizz/p6jd2r0s/24/) из задания

**Comment by izy-13** [comment]
Замечания устранены последним пушем данных (просьба проверить подгружаются ли картинки)
